- 
    project:
        check:
            jobs:
                - thoth-coala
        gate:
            queue: thoth-station/core
            jobs:
                - thoth-coala
        kebechet-auto-gate:
            queue: thoth-station/core
            jobs:
                - thoth-coala
        periodic:
            jobs:
                - 
                    thoth-behave:
                        vars:
                            thoth_environment:
                                THOTH_USER_API_URL: test.thoth-station.ninja
