-
    project:
        check:
            jobs:
                - noop 
        gate:
            queue: thoth-station/core
            jobs:
                - noop 
        kebechet-auto-gate:
            queue: thoth-station/core
            jobs:
                - noop 
        post:
            jobs:
                -
                    thoth-behave:
                        vars:
                            thoth_environment:
                                THOTH_USER_API_HOST: test.thoth-station.ninja
                                THOTH_MANAGEMENT_API_HOST: management.test.thoth-station.ninja
        periodic:
            jobs:
                -
                    thoth-behave:
                        vars:
                            thoth_environment:
                                THOTH_USER_API_HOST: test.thoth-station.ninja
                                THOTH_MANAGEMENT_API_HOST: management.test.thoth-station.ninja
