---
- project:
    check:
      jobs:
# This only works on public repositories
#        - "thoth-github-wip"
        - "thoth-coala"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
