---
- project:
    check:
      jobs:
# This only works on public repositories
#        - "thoth-github-wip"
        - "thoth-coala"
        - "thoth-behave"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"

- job:
    name: "thoth-behave"
    description: |
      This job will use behave to run some integration tests.
    vars:
      thoth_environment: "test"
    run: playbooks/behave.yaml